name: resume_builder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.4.0
  firebase_core: ^2.19.0
  google_sign_in: ^6.1.0
  google_nav_bar: ^5.0.0
  line_icons: ^2.0.1
  pdf: ^3.6.0
  path_provider: ^2.1.2
  printing:
    git:
      url: https://github.com/iamashish1/dart_pdf.git
      path: printing
  firebase_storage: ^11.0.0
  intl: 0.18.1
  flutter_bloc: ^8.0.0
  cloud_firestore: ^4.0.0
  path: 1.8.2
  firebase_app_check: ^0.2.0
  gap: ^3.0.0
  flutter_launcher_icons: ^0.13.0
  google_fonts: ^6.0.0
  fluttertoast: ^8.0.0
  shared_preferences: ^2.0.0
  dartz: ^0.10.0
  equatable: ^2.0.0
  freezed: ^2.0.0
  freezed_annotation: ^2.0.0
  google_mobile_ads: ^2.0.0
  flutter_dotenv: ^5.0.0
  open_file_plus: ^3.0.0
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/font/
    - assets/icons/
    - .env

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-Bold.ttf
          weight: 700
        - asset: assets/font/Manrope-ExtraBold.ttf
        - asset: assets/font/Manrope-Light.ttf
    - family: Montserrat
      fonts:
       - asset: assets/font/Montserrat-Regular.ttf
       - asset: assets/font/Montserrat-Bold.ttf
       - asset: assets/font/Montserrat-Light.ttf
       - asset: assets/font/Montserrat-Italic.ttf
